### PR TITLE
Sanitizing config filename.

### PR DESCRIPTION
**Pull request by endersonmaia**
This way we get $FILENAME.$FORMAT.$TARGET.

[ci skip]

### CODE REVIEW

**Comment by TeatroIO** [comment]
I've prepared a stage to preview changes. <a href='http://endersonmaia-sanitize-config-filenames.alagoasdevday-call4papers-3062b296e4351a66c3e5.ttrcloud.com' target='_blank'>Open stage</a> or <a href='http://endersonmaia-sanitize-config-filenames.alagoasdevday-call4papers-3062b296e4351a66c3e5.ttrcloud.com/teatro.log' target='_blank'>view logs</a>.

**Comment by gmmcal** [comment]
don't forget to update README and other text files and add to CHANGELOG :smile:

**Comment by endersonmaia** [comment]
Again, I know! But I first need to create the PR to know it's number. ;)

will do it now!

**Comment by gmmcal** [comment]
@endersonmaia you forgot to update the README instructions

**Pull request merged**
